FRANCINE YSABELLE BORROMEO

In [1]:
import random
import numpy as np

def determinant(matrix):
    """
    Finds the determinant of an n x n matrix using Laplace expansion.

    Parameters:
    - matrix (list of lists): The input matrix.

    Returns:
    - determinant (float): The determinant of the matrix.
    """
    size = len(matrix)

    # Base case: If the matrix is 1x1, return the only element
    if size == 1:
        return matrix[0][0]

    # Base case: If the matrix is 2x2, return the determinant using the formula
    if size == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]

    det = 0
    for col in range(size):
        # Calculate the cofactor
        cofactor = (-1) ** col * matrix[0][col] * determinant(minor(matrix, 0, col))
        det += cofactor

    return det

def minor(matrix, row, col):
    """
    Returns the minor matrix obtained by removing the specified row and column.

    Parameters:
    - matrix (list of lists): The input matrix.
    - row (int): The row to be removed.
    - col (int): The column to be removed.

    Returns:
    - minor_matrix (list of lists): The minor matrix.
    """
    return [row[:col] + row[col + 1:] for row in (matrix[:row] + matrix[row + 1:])]

def eigendecomposition(matrix):
    """
    Finds the eigenvectors and eigenvalues of an n x n matrix.

    Parameters:
    - matrix (list of lists): The input matrix.

    Returns:
    - eigenvalues (numpy array): The eigenvalues of the matrix.
    - eigenvectors (numpy array): The eigenvectors of the matrix.
    """
    matrix_np = np.array(matrix)
    eigenvalues, eigenvectors = np.linalg.eig(matrix_np)
    return eigenvalues, eigenvectors

if __name__ == "__main__":
    # Generate a random 3x3 matrix as an example
    n = 3
    random_matrix = [[random.randint(1, 10) for _ in range(n)] for _ in range(n)]

    # Test determinant function
    det_result = determinant(random_matrix)
    print(f"The determinant of the matrix is: {det_result}")

    # Test eigendecomposition function
    eigenvalues, eigenvectors = eigendecomposition(random_matrix)
    print(f"\nEigenvalues:\n{eigenvalues}")
    print(f"\nEigenvectors:\n{eigenvectors}")


The determinant of the matrix is: 49

Eigenvalues:
[16.51088107 -2.09282994 -1.41805113]

Eigenvectors:
[[-0.2726507  -0.79229412 -0.56823935]
 [-0.76654219  0.37005334 -0.06657491]
 [-0.58144188  0.4851088   0.82016573]]
